import {
  addressDetails,
  addresses,
  addressSuggestions,
  apartments,
  coupons,
  orderAddressTableEntries,
  orderDetails,
  orders,
  partnerDetails,
  partners,
  productVariants,
  projectAppointments,
  projectDetails,
  projects,
  projectSalesPartners,
  projectStorePartners,
  userDetails,
  users,
  orderOptions,
  tariffInformation,
} from './api';

export const database = {
  orders,
  orderDetails,
  addressDetails,
  addresses,
  projects,
  projectDetails,
  partners,
  userDetails,
  users,
  partnerDetails,
  apartments,
  projectSalesPartners,
  projectStorePartners,
  projectAppointments,
  productVariants,
  orderAddressTableEntries,
  addressSuggestions,
  coupons,
  tariffInformation,
  orderOptions,
};
